### ISSUE TITLE
Use cases for linking borrowed URIs to AC documentation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#16]
```
Specify detailed use cases for links from borrowed URIs into AC documentation 
instead of the http dereference

```

Original issue reported on code.google.com by `morris.bob` on 15 Jul 2012 at 1:34
- Blocked on: #15

**Comment by baskaufs** [comment]
I'm going to close this issue since I think we now have a robust means for people to link to metadata about borrowed terms.  The graph model for machine-readable metadata as described in the Standards Documentation Spec shows how all terms (borrowed and not) can be discovered via query and the human-readable documents will (eventually) have stable anchors for each term.  For example: https://github.com/tdwg/ac/blob/documentation-conversion/doc/termlist.md#Iptc4xmpExt_CVterm takes you to Iptc4xmpExt:CVterm .  This URL is currently ugly, but once content negotiation is working, applying the same hash ID to the permanent URI of the term list should jump people to the term description.  So although this isn't currently working, it will get fixed on its own as TDWG implements URI dereferencing with content negotiation.
