### ISSUE TITLE
Problems with Iptc4xmpExt:CVterm

### ISSUE THREAD

**Issue by edwbaker** [tdwg/ac#230]
Following on from discussions at https://github.com/tdwg/camtrap-dp/issues/191

See also [early discussion of potential problem](https://code.google.com/archive/p/auduboncore/issues/88)

Various possibilities to improve the situation here:
- [Provide a controlled vocabulary in Audubon Core](https://github.com/tdwg/camtrap-dp/issues/191#issuecomment-1030667473)
- [Minting new terms in the ac namespace](https://github.com/tdwg/camtrap-dp/issues/191#issuecomment-1030682320)
- [Using dc:subject / dcterms:subject](https://github.com/tdwg/camtrap-dp/issues/191#issuecomment-1030686367)

**Comment by baskaufs** [comment]
I've been thinking some about this issue again in the context of the severe need for people to describe that an image or a ROI is a label. #200 

Despite the various potential problems related to whether our use of `Iptc4xmpExt:CVterm` is exactly correct based on the IPTC specs, it has been a part of AC for a long time and from the standpoint of stability, it might be best to just keep it rather than coming up with a new term or recommending something else. 

I was thinking a bit about how I've seen `dcterms:subject` being used in other contexts. It seems like it is more commonly used to describe the topic of something than to describe the actual thing itself. For example, a photo of people carrying signs in a protest might have the subject as "protest", whereas an actual description of what's in the photo would be things like "person", "sign", "flag", "fire", etc. In the library realm, one would probably use Library of Congress subject headings as values, and again it would be more what a book or images is "about" rather than what's depicted in it. So I'm thinking that dcterms:subject isn't the best thing to use in this case where we are actually trying to describe what's in the image.

It seems to me that a reasonable course of action that would mostly be consistent with existing use but also promote clarity would be to do the following:

1. Recommend that `dcterms:description` be used for a textual description. This could be free text or a controlled value string if people preferred.
2. Recommend that 'Iptc4xmpExt:CVterm` be used with an unabbreviated IRI. That's allowable under the current AC guidelines and (probably) consistent with the intent of the IPTC (although they seem to suggest using a namespace abbreviation rather than a full URI). 
3. Mint an AC controlled vocabulary for the terms that we know we need right now. That would include things typically designated in specimen images such as label and color bar. In the interest of closing #166, we could also include something for "habitat". Would we also include "organism", "organism part", or something else to indicate that the ROI or whole image primarily includes something that would subsequently be described by `subjectPart` and `subjectOrientation`. 

This would be a bit at odds with the existing pattern of `x` and `xLiteral`, but I think it makes more sense to use the terms we already have.

**Comment by edwbaker** [comment]
Will be closed by #246
