### ISSUE TITLE
"leaf" orientation for bryophytes

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#238]
It was suggested that "leaf" be used as a subject part for bryophytes, with possible orientations "lateral" and "ventral". However, previously "leaf" had possible orientations "abaxial" and "adaxial". How do we handle this conflict? Possibilities:

1. Add "lateral" and "ventral" to the possible orientations for "leaf". However, this might confuse the issue for plants where the two reasonable orientations are abaxial and adaxial, since those may be less familiar terms for non-specialists.
2. Create a different part type from "leaf", apply it specifically to bryophytes, and give it those two values.

**Comment by nielsklazenga** [comment]
`abaxial` and `adaxial` are the sides of the leaves and are the appropriate terms to use in `subjectOrientation`, although I would not use the terms by themselves, but always as `abaxial side` or `adaxial side`. `ventral` and `dorsal` are often used instead of `abaxial` and `adaxial`. I would avoid them in mosses, as the leaves are mostly not horizontally spreading, so it is easier to see which side of the leave faces the axis and which side faces away from it, but they are probably the more useful terms in liverworts, especially the thallose ones, and hornworts. I do not see a use for `lateral` in `subjectOrientation` regarding leaves in bryophyte, but you've got of course lateral sections through capsules, peristome teeth, etc. and in Polytrichaceae there are diagnostic characters in the lateral view of the lamellae. [BTW. do you have something for cross sections?]

`dorsal`, `ventral` and `lateral` are a bit problematic as well, as they are also used to indicate which side of the stem or branch the leaves are on. So, like with `adaxial` and `abaxial`, you should never just use the adjective.

**Comment by baskaufs** [comment]
@nielsklazenga take a look at [this new version](https://github.com/tdwg/ac/blob/cec167d4fc85b5edaa2559572e5d1c060e4dcb3a/views/code/subjectOrientation/subjectOrientation_cv.csv).

Keep in mind that the controlled string is neither the label nor the definition of the controlled value term. The labels all say "x side", and the definitions also say that one is viewing the side of the organism or part that is oriented in a particular direction. The controlled value string is a memorable "shorthand" for the term, but not a complete label or definition in itself.

As you can see from my comment in #239, I've opted for two simplified terms labeled "upper side" and "lower side". The definitions clarify that "upper side" is the side toward the axis if there is one (adaxial) and the "lower side" is the side away from the axis if there is one (abaxial). I realize that this is messy for vertically oriented leaves, but it avoids a proliferation of terms and the usage notes clarify that upper side should also be used for plants and fungi that don't have an axis. This gives us a single pair of values to use for all plants and fungi that applies to the side pointing up or towards the axis and the side pointing down or away from the axis. It's a practical rather than technical solution, but I think it may be easier for non-technical people to use if they are the ones given the job of categorizing images.

I'm open to other alternatives if someone can make a different proposal and defend why it's better than this one.

**Comment by baskaufs** [comment]
This issue was resolved in https://github.com/tdwg/ac/commit/cec167d4fc85b5edaa2559572e5d1c060e4dcb3a by changing the terms from adaxial and abaxial to upper side and lower side, making them more broadly applicable in the future if terms for [ferns](https://github.com/tdwg/ac/tree/master/views/candidate_terms/ferns) and [bryophytes](https://github.com/tdwg/ac/tree/master/views/candidate_terms/bryophytes) are added.
