### ISSUE TITLE
Example for identification keys/tools

### ISSUE THREAD

**Issue by larsgw** [tdwg/ac#251]
I am interested in using Audiovisual Core to describe identification keys and other tools, but I cannot find an example of this. I don't know if I misunderstood the purpose of the standard, is it only for images/videos/audio? If interactive identification key apps are included, what about regular identification keys consisting of text and/or images? I expect the data on the taxonomic and geographic scope to be relevant for both.

**Comment by baskaufs** [comment]
I believe that identification keys were considered to be within the scope of Audiovisual Core when it was originally envisioned. There is a value for the `ac:subtype` term of <http://rs.tdwg.org/acsubtype/values/IdentificationKey>, which indicates that keys could potentially be described using AC.

However, like several other media types, the vocabulary hasn't really been developed to handle that. The original vocabulary was primarily oriented around describing still images. Since then, it has been expanded to do a better job of describing sound and to some extent video. But no one has really worked on keys. I think that would be a good addition, particularly since effective keys can include media as an aid. If this is something that interests you, we could probably discuss it at a Maintenance Group meeting. Pinging @edwbaker about this.

**Comment by edwbaker** [comment]
Agree it’s worth having a discussion about. It seems like just labelling something as an identification key should be simple. However, going into detail about the key might be a different (much larger) thing to address. I’ll add it to the agenda.

**Comment by larsgw** [comment]
If it helps: the non-bibliographical non-access detail that I provide is to describe the scope with one or both of the following.

  1. A combination of a higher taxon and geography, as well as less common restrictions like life stage, sex, habitat (especially "aquatic species"), etc.; or
  2. A full list of identifiable units: taxa, or further distinguished by sex, life stage, etc.

**Comment by edwbaker** [comment]
Following discussion at the 2024 Working Group meeting, I am closing this issue as, at present, we don't have the capacity to complete this. We would be happy to revisit this if there is enough interest to form a task group.

**Comment by larsgw** [comment]
Thank you for discussing it! Maybe the work could be combined with updating SDD. I will see if there are some interested parties over the coming months.

**Comment by klausriede** [comment]
I think it is an important issue to be taken up! In fact the vocabulary used in the keys could be useful to extend the vocabulary envisioned here! The key by Ragge based on acoustic features might be a good starting point and finger exercise!

**Comment by edwbaker** [comment]
If there is a group of people who are willing to take on this work (which it seems that there might be) then we can facilitate a Task Group.

**Comment by larsgw** [comment]
> The key by Ragge based on acoustic features might be a good starting point and finger exercise!

To encode in SDD, you mean? I have a script to create an SDD file for _Shchytnyky_ [Shield bugs] by V. G. Puchkov (1961), and a script to ingest that file in Pandoc, in https://github.com/larsgw/pentatomoidea-nymphs. I see now I haven't included the actual SDD file in the repository though.
