### ISSUE TITLE
Table cell boundaries not visible under new website theme

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ac#256]
**Page(s) where issue occurs** 

> https://ac.tdwg.org/structure/#321-example-of-a-table-with-each-service-access-point-in-a-separate-row-non-normative

**Issue description**

> The current styling of the tables has dropped the cell boundary lines. So it's no longer clear that the example is a table. Not sure if this is something to be fixed on the CSS/theme end or if it should be hard-coded in the Markdown document

**Comment by peterdesmet** [comment]
The is because that page (and probably others) defines a class for that table (and probably others):

https://github.com/tdwg/ac/blob/8d4196fb42ee35dbe5a22915ca15759e0f8d0d23/docs/structure/index.md?plain=1#L248

`table-responsive` is a wrong Bootstrap class to use for tables. It should be used for a parent div of the table. Petridish will add [those divs automatically](https://github.com/peterdesmet/petridish/blob/d656bf7541266561fcdd3ee69798d038472bf90b/_layouts/base.html#L14-L17), so it's not necessary to do it manually. Petridish will also automatically add the class `table` to tables _unless_ (as is the case here) a class is already defined.

So the solution would be to change to `<table>` (and have Petridish add the class `table`) or hardcode as `<table class="table">`. My preference is the first, so contributors don't have to worry about adding classes or not. The result will look like this:

<img width="762" alt="Screenshot 2023-05-03 at 16 55 08" src="https://user-images.githubusercontent.com/600993/235955325-14a02ef1-caa1-4618-8c7a-7155bc5ae29a.png">

**Comment by baskaufs** [comment]
Thanks @peterdesmet . I'm not sure how that class was added to the table element. Probably just got copied from somewhere. I will fix the tags and see if there are other changes needed in other documents.

**Comment by baskaufs** [comment]
fixed
