### ISSUE TITLE
In RDF, should SKOS be used for ac:layer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#26]
```
In the trivial RDF rendering at 
http://species-id.net/wiki/Audubon_Core_Term_List_RDF_Version, the layer is 
represented as an ac term.  Should it be rendered as a SKOS property instead?
```

Original issue reported on code.google.com by `morris.bob` on 1 Oct 2012 at 2:03

**Comment by baskaufs** [comment]
OK, currently there is a term called tdwgutility:layer that is being used to provide the information about the layer, with additional terms for "required" and "repeatable"  See https://github.com/tdwg/rs.tdwg.org/blob/split_ac_terms/Iptc4xmpExt-for-ac/Iptc4xmpExt-for-ac-column-mappings.csv for example.  The actual sorting into categories is done by tdwgutility:organizedInClass, information that's used to categorize terms in the autogenerated page https://github.com/tdwg/ac/blob/documentation-conversion/doc/termlist.md  See https://github.com/tdwg/ac/blob/documentation-conversion/code/build_page.py for how it's being done.  

I don't think we need to go down the full SKOS route with AC terms since SKOS collections are intended for concepts (i.e. controlled vocabulary terms) rather than properties as we have in AC.
