### ISSUE TITLE
Update wiki/AboutIssueTracker

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tdwg/ac#89]
```
https://code.google.com/p/auduboncore/wiki/AboutIssueTracker review and 
updating in view of acceptance
```

Original issue reported on code.google.com by `morris.bob` on 16 Jan 2014 at 1:35

**Comment by baskaufs** [comment]
So it's my opinion that the Vocab Management Spec allows us to make this kind of correction without any sort of approval, since its a correction, or cosmetic change that really has no impact on stability or interoperability.  See section 3.4.1 and 3.4.3 at https://github.com/tdwg/vocab/blob/master/vms/maintenance-specification.md#34-changes-to-documents-supporting-the-vocabulary

**Comment by ramorrismorris** [comment]
That was my recollection. I can do it and close the issue.

**Comment by baskaufs** [comment]
I have created a "historical" directory and moved the Hangout meetings and Public Review comment records into it along with the old Wiki documents that may still contain useful content.  At least one of the documents in the "doc" directory of the document-conversion branch has the updated link to the correct Issue tracker (github rather than Google Code).  When reviewing the other documents, we can decide if any others need a link to it.  I think the main thing is to make sure that the landing page has appropriate instructions for commenting and opening issues.
